create table if not exists xll_estado_finanzas(

	id						integer AUTO_INCREMENT PRIMARY KEY,
    fk_tercero				integer NOT NULL,
    ventaAnual				double	NOT NULL,
    costoVentas				double	NOT NULL,
    utilidadAnual			double	NOT NULL,
    clientes				double	NOT NULL,
    inventario				double	NOT NULL,
    actCirculante			double	NOT NULL,
    pasCirculante			double	NOT NULL,
    totalActivos			double	NOT NULL,
    totalPasivo				double	NOT NULL,
    proveedores				double	NOT NULL,
    credCortoPlazo			double	NOT NULL,
    credLargoPlazo			double	NOT NULL,
    saldPM1					double	NOT NULL,
    saldPM2					double	NOT NULL,
    saldPM3					double	NOT NULL,
    saldPM4					double	NOT NULL,
    saldPM5					double	NOT NULL,
    saldPM6					double	NOT NULL,
    ingrM1					double	NOT NULL,
    ingrM2					double	NOT NULL,
    ingrM3					double	NOT NULL,
    ingrM4					double	NOT NULL,
    ingrM5					double	NOT NULL,
    ingrM6					double	NOT NULL
) ENGINE=innodb;